# This value is used to report None
NEGATIVE = 2 ** 21 - 1 # 2097151

# Map between integers and teams
TEAM_VALUES = {
  2: "radiant",
  3: "dire",
  5: "spectator",
  0: None,
  1: None,
}

WINNER_VALUES = {
    2: "radiant",
    3: "dire",
    5: None
}

LIFE_STATE_VALUES = {
  0: "alive",
  1: "dying",
  2: "dead",
  3: "respawnable",
  4: "discardbody"
}

GAME_STATE_VALUES = {
  1: "loading",
  2: "draft",
  3: "strategy time",
  4: "pregame",
  5: "game",
  6: "postgame",
  7: "disconnect"
}

GAME_MODE_VALUES = {
    0: "none",
    1: "all pick",
    2: "captain's mode",
    3: "random draft",
    4: "single draft",
    5: "all random",
    6: "intro",
    7: "diretide",
    8: "reverse captain's mode",
    9: "greeviling",
    10: "tutorial",
    11: "mid only",
    12: "least played",
    13: "new player pool",
    14: "compendium matchmaking"
}

def generate_pick_values():
    b = "ban"
    p = "pick"
    return {
        1: "all pick",
        2: "single draft",
        4: "random draft",
        27: "all random",

        # CM values
        6: (b, 1),
        7: (b, 2),
        8: (b, 3),
        9: (b, 4),
        16: (p, 1),
        17: (p, 2),
        18: (p, 3),
        19: (p, 4),
        10: (b, 5),
        11: (b, 6),
        12: (b, 7),
        13: (b, 8),
        20: (p, 5),
        21: (p, 6),
        22: (p, 7),
        23: (p, 8),
        14: (b, 9),
        15: (b, 10),
        24: (p, 9),
        25: (p, 10),
        26: "complete"
    }

PICK_VALUES = generate_pick_values()

COMBAT_LOG_TYPES = {
    0: "damage",
    1: "heal",
    2: "modifier added",
    3: "modifier removed",
    4: "death"
}

HERO_VALUES = {
    0: None,
    1: "Antimage",
    2: "Axe",
    3: "Bane",
    4: "Bloodseeker",
    5: "Crystal Maiden",
    6: "Drow Ranger",
    7: "Earthshaker",
    8: "Juggernaut",
    9: "Mirana",
    10: "Morphling",
    11: "Nevermore",
    12: "Phantom Lancer",
    13: "Puck",
    14: "Pudge",
    15: "Razor",
    16: "Sand King",
    17: "Storm Spirit",
    18: "Sven",
    19: "Tiny",
    20: "Vengeful Spirit",
    21: "Windrunner",
    22: "Zuus",
    23: "Kunkka",
    25: "Lina",
    26: "Lion",
    27: "Shadow Shaman",
    28: "Slardar",
    29: "Tidehunter",
    30: "Witch Doctor",
    31: "Lich",
    32: "Riki",
    33: "Enigma",
    34: "Tinker",
    35: "Sniper",
    36: "Necrolyte",
    37: "Warlock",
    38: "Beastmaster",
    39: "Queen of Pain",
    40: "Venomancer",
    41: "Faceless Void",
    42: "Skeleton King",
    43: "Death Prophet",
    44: "Phantom Assassin",
    45: "Pugna",
    46: "Templar Assassin",
    47: "Viper",
    48: "Luna",
    49: "Dragon Knight",
    50: "Dazzle",
    51: "Rattletrap",
    52: "Leshrac",
    53: "Furion",
    54: "Life Stealer",
    55: "Dark Seer",
    56: "Clinkz",
    57: "Omniknight",
    58: "Enchantress",
    59: "Huskar",
    60: "Night Stalker",
    61: "Broodmother",
    62: "Bounty Hunter",
    63: "Weaver",
    64: "Jakiro",
    65: "Batrider",
    66: "Chen",
    67: "Spectre",
    68: "Ancient Apparition",
    69: "Doom Bringer",
    70: "Ursa",
    71: "Spirit Breaker",
    72: "Gyrocopter",
    73: "Alchemist",
    74: "Invoker",
    75: "Silencer",
    76: "Obsidian Destroyer",
    77: "Lycan",
    78: "Brewmaster",
    79: "Shadow Demon",
    80: "Lone Druid",
    81: "Chaos Knight",
    82: "Meepo",
    83: "Treant",
    84: "Ogre Magi",
    85: "Undying",
    86: "Rubick",
    87: "Disruptor",
    88: "Nyx Assassin",
    89: "Naga Siren",
    90: "Keeper of the Light",
    91: "Wisp",
    92: "Visage",
    93: "Slark",
    94: "Medusa",
    95: "Troll Warlord",
    96: "Centaur",
    97: "Magnataur",
    98: "Shredder",
    99: "Bristleback",
    100: "Tusk",
    101: "Skywrath Mage",
    102: "Abaddon",
    103: "Elder Titan",
    104: "Legion Commander",
    106: "Ember Spirit",
    107: "Earth Spirit",
    108: "Abyssal Underlord",
}